server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
#          filters:
#            - name: JwtAuthenticationFilter
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/restaurants/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/oauth2/jwks

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 900000
      refresh-token:
        expiration: 6040000000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG