server:
  port: 8086

spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      stream:
        bindings:
            destination: order-events
            contentType: application/json
        rabbit:
          bindings:
            orderPlacedOutput:
              producer:
                exchange-type: topic
                routing-key-expression: "'order.placed'"
                producer:
                  transacted: false
                  republish-to-dlq: true
                  return-data-type: Full
        rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest

  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: baaki
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.bytebites.orderservice: DEBUG