spring:
  application:
    name: restaurant-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka